spring:
  rabbitmq:
    host: 8.134.12.132
    port: 5672
    username: admin
    password: admin
    virtual-host: /
    # 发布确认
    publisher-confirm-type: correlated
    # 消息退回
    publisher-returns: true
